// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPmhaLfBYBF4F33AJN-GAISR4wUDuu2ac',
    appId: '1:307727384606:web:0bff8d67d8c3658f3eae0f',
    messagingSenderId: '307727384606',
    projectId: 'parkify-38e62',
    authDomain: 'parkify-38e62.firebaseapp.com',
    storageBucket: 'parkify-38e62.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1tomAz-6fcieUZbHn0iWeqqBian-e9QE',
    appId: '1:307727384606:ios:60392a09aad096b13eae0f',
    messagingSenderId: '307727384606',
    projectId: 'parkify-38e62',
    storageBucket: 'parkify-38e62.firebasestorage.app',
    iosBundleId: 'com.example.smartparkify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPmhaLfBYBF4F33AJN-GAISR4wUDuu2ac',
    appId: '1:307727384606:web:5490fdbeff008fca3eae0f',
    messagingSenderId: '307727384606',
    projectId: 'parkify-38e62',
    authDomain: 'parkify-38e62.firebaseapp.com',
    storageBucket: 'parkify-38e62.firebasestorage.app',
  );
}
